# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"%\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x9e\x01\n\x04Span\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x12\n\nservice_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\"\n\x07metrics\x18\x05 \x03(\x0b\x32\x11.telemetry.Metric\x12\x14\n\x0c\x61nomaly_type\x18\x06 \x01(\t\x12\x12\n\nis_anomaly\x18\x07 \x01(\x08\"+\n\tSpanBatch\x12\x1e\n\x05spans\x18\x01 \x03(\x0b\x32\x0f.telemetry.Span\"J\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0espans_accepted\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2V\n\x10TelemetryService\x12\x42\n\x0fIngestSpanBatch\x12\x14.telemetry.SpanBatch\x1a\x19.telemetry.IngestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRIC']._serialized_start=30
  _globals['_METRIC']._serialized_end=67
  _globals['_SPAN']._serialized_start=70
  _globals['_SPAN']._serialized_end=228
  _globals['_SPANBATCH']._serialized_start=230
  _globals['_SPANBATCH']._serialized_end=273
  _globals['_INGESTRESPONSE']._serialized_start=275
  _globals['_INGESTRESPONSE']._serialized_end=349
  _globals['_TELEMETRYSERVICE']._serialized_start=351
  _globals['_TELEMETRYSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
