# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\tmlservice\"t\n\x10InferenceRequest\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x65\x61ture_vector\x18\x02 \x03(\x02\x12\x11\n\twindow_id\x18\x03 \x01(\t\x12\x0f\n\x07span_id\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\"\xac\x01\n\x0fInferenceResult\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x15\n\ranomaly_score\x18\x02 \x01(\x02\x12\x12\n\nmodel_used\x18\x03 \x01(\t\x12\x12\n\nis_anomaly\x18\x04 \x01(\x08\x12\x12\n\nlatency_ms\x18\x05 \x01(\x02\x12\x14\n\x0c\x61nomaly_type\x18\x06 \x01(\t\x12\x1c\n\x14reconstruction_error\x18\x07 \x01(\x02\x32V\n\x12MLInferenceService\x12@\n\x05Infer\x12\x1b.mlservice.InferenceRequest\x1a\x1a.mlservice.InferenceResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=31
  _globals['_INFERENCEREQUEST']._serialized_end=147
  _globals['_INFERENCERESULT']._serialized_start=150
  _globals['_INFERENCERESULT']._serialized_end=322
  _globals['_MLINFERENCESERVICE']._serialized_start=324
  _globals['_MLINFERENCESERVICE']._serialized_end=410
# @@protoc_insertion_point(module_scope)
